version: "3"
services:
  web:
    build:
      context: .
      dockerfile: api/Dockerfile
    restart: always
    volumes:
      - ./data:/api/data
    ports:
     - "5000:5000"
    depends_on:
      - redis
  worker:
    build:
      context: .
      dockerfile: celery-queue/Dockerfile
    entrypoint:  celery -A tasks worker --beat --loglevel=info
    volumes:
      - ./data:/queue/data
    depends_on:
      - redis
  monitor:
    build:
      context: .
      dockerfile: celery-queue/Dockerfile
    ports:
     - "5555:5555"
    entrypoint: flower
    command:  -A tasks --port=5555 --broker=redis://redis:6379/0
    depends_on:
      - redis
  redis:
    image: redis